nginx:
    build: ./nginx
    container_name: nginx
    ports:
        - 80:80
    links:
        - mysql
        - php
    volumes:
        - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./data/nginx/conf.d/:/etc/nginx/conf.d/
    volumes_from:
        - php
    restart: always

php:
    build: ./php
    container_name: php
    ports:
        - 9000:9000
    links:
        - mysql
    volumes:
        - ./data/webroot:/var/www/html
    restart: always

mysql:
    build: ./mysql
    container_name: mysql
    ports:
        - 3306:3306
    volumes:
        - ./data/mysql:/var/lib/mysql
        - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
    restart: always

redis:
    build: ./redis
    container_name: redis
    ports:
      - 6379:6379
    restart: always

lovehate:
    build: .
    container_name: lovehate
    dockerfile: Dockerfile-lovehate
    ports:
        - 8001:8000
    restart: always

