FROM python:3.5

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
RUN apt-get update && apt-get install -y \
    vim
COPY src/lovehate /usr/src/app
RUN mkdir /usr/src/app/server/logs
RUN touch /usr/src/app/server/logs/debug.log
RUN mkdir /root/.pip
COPY configs/pip/pip.conf /root/.pip/
RUN pip install --no-cache-dir -r requirement.txt
WORKDIR /usr/src/app/server
RUN gunicorn server.wsgi:application -k gevent -b 127.0.0.1:8000 -w 3 -t 600 --max-requests=500  --worker-connections=1000 --log-level=debug
EXPOSE 8000
#CMD ["/usr/bin/python"]
